### ISSUE TITLE
Using LabelEncoder

### ISSUE THREAD

**Issue by crownedone** [crownedone/mushrooms#1]
What is the benefit of using labelEncoder compared to hash for strings?
If we do pca, will there be a difference in results?

**Comment by kevinzagalo** [comment]
@crownedone PCA will select a linear combination of your variables. That means that it will be more representative of the importance of each value possible.

**Comment by crownedone** [comment]
Actually it can't, is there another LabelEncoder out there? 
I thought it would add a dimension for each different string in the data, but it can only substitute strings with numbers.

**Comment by kevinzagalo** [comment]
you're looking for this maybe ? https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelBinarizer.html

**Comment by crownedone** [comment]
Yes, that looks like it ;) Thanks!
